services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./packages/cli/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: 'true'
      - key: N8N_BASIC_AUTH_USER
        value: 'admin'
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 'yourpassword'
      - key: WEBHOOK_URL
        value: 'https://n8n.onrender.com/'
      - key: EXECUTIONS_PROCESS
        value: 'main'
      - key: GENERIC_TIMEZONE
        value: 'Asia/Kathmandu'
